version: '2.1'

volumes:
  pgdata:
  walletstore:
  prometheus-storage:
  grafana-storage:
  portainer-storage:

networks:
  test:

services:

  explorerdb.art-nft.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.art-nft.com
    hostname: explorerdb.art-nft.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - test

  explorer.art-nft.com:
    image: hyperledger/explorer:latest
    container_name: explorer.art-nft.com
    hostname: explorer.art-nft.com
    environment:
      - DATABASE_HOST=explorerdb.art-nft.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ../config/explorer/config.json:/opt/explorer/app/platform/fabric/config.json
      - ../config/explorer/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../organizations/peerOrganizations/auctionhouse.art-nft.com:/tmp/crypto/peerOrganizations/auctionhouse.art-nft.com
      - walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.art-nft.com:
        condition: service_healthy
    networks:
      - test

  proms.art-nft.com:
    container_name: proms.art-nft.com
    image: prom/prometheus:latest
    volumes:
      - ../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    ports:
      - '9090:9090'
    networks:
      - test

  grafana.art-nft.com:
    container_name: grafana.art-nft.com
    image: grafana/grafana:latest
    volumes:
      - ../config/grafana/art-nft-grafana-dashboard.json:/var/lib/grafana/dashboards/mydashboard.json
      - ../config/grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    ports:
      - '3000:3000'
    networks:
      - test
  
  portainer.art-nft.com:
    image: portainer/portainer
    container_name: portainer.art-nft.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-storage:/data
    ports:
      - 9000:9000
    networks: 
      test: