version: '2.1'

networks:
  test:

services:
  hlf-fabric-client.auctionhouse.art-nft.com:
    container_name: hlf-fabric-client.auctionhouse.art-nft.com
    image: anandbanik/hlf-rest-client:1.2.2
    environment:
      - spring_profiles_active=container
      - fabric_localhostReportAddress=false
      - fabric_orgConnectionConfig_filename=connection-auctionhouse.yaml
      - fabric_wallet_clientUser_name=clientUser
    ports:
      - 8081:8080
    volumes:
      - ../config/rest-client/application.yml:/usr/local/config/application.yml
      - ../credentials/wallet:/usr/local/config/wallet
      - ../organizations/peerOrganizations/auctionhouse.art-nft.com/connection-auctionhouse-ext.yaml:/usr/local/config/connection-auctionhouse.yaml
    networks:
      - test